"""change geo to float

Revision ID: 74e94277090b
Revises: c2cad786bf9c
Create Date: 2026-04-22 17:56:55.201083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e94277090b'
down_revision: Union[str, Sequence[str], None] = 'c2cad786bf9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('readingmaster', 'geo_lat',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('readingmaster', 'geo_long',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('readingmaster', 'geo_long',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
    op.alter_column('readingmaster', 'geo_lat',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
    # ### end Alembic commands ###
