"""initial

Revision ID: c2cad786bf9c
Revises: 
Create Date: 2026-04-22 16:35:23.507518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2cad786bf9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mr_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mr_id', sa.String(), nullable=False),
    sa.Column('mr_pswd', sa.String(), nullable=False),
    sa.Column('mr_name', sa.String(), nullable=True),
    sa.Column('mr_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mr_registration_id'), 'mr_registration', ['id'], unique=False)
    op.create_index(op.f('ix_mr_registration_mr_id'), 'mr_registration', ['mr_id'], unique=True)
    op.create_table('readingmaster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rdng_img', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('mr_id', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('geo_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('geo_long', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mr_id'], ['mr_registration.mr_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readingmaster_transaction_id'), 'readingmaster', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readingmaster_transaction_id'), table_name='readingmaster')
    op.drop_table('readingmaster')
    op.drop_index(op.f('ix_mr_registration_mr_id'), table_name='mr_registration')
    op.drop_index(op.f('ix_mr_registration_id'), table_name='mr_registration')
    op.drop_table('mr_registration')
    # ### end Alembic commands ###
