"""add consumer_id to readingmaster

Revision ID: d0a686334194
Revises: 74e94277090b
Create Date: 2026-05-29 14:51:00.089202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a686334194'
down_revision: Union[str, Sequence[str], None] = '74e94277090b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readingmaster', sa.Column('consumer_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_readingmaster_consumer_id'), 'readingmaster', ['consumer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readingmaster_consumer_id'), table_name='readingmaster')
    op.drop_column('readingmaster', 'consumer_id')
    # ### end Alembic commands ###
